// Generated by nitro
import type { Serialize, Simplify } from "nitro/types";
declare module "nitro/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/cron': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/cron.get').default>>>>
    }
    '/process-user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/routes/process-user.get').default>>>>
    }
    '/_nitro/tasks/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitro/dist/runtime/internal/routes/dev-tasks').default>>>>
    }
  }
}
export {}